pipeline:
  name: Build test2
  identifier: Build_annieastronomer_test2_1730489260765
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: install cli
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Bash
                    command: |-
                      jobs:

                        build_image_and_deploy:
                          docker:
                            - image: cimg/base:stable
                          # Add steps to the job
                          # See: https://circleci.com/docs/2.0/configuration-reference/#steps
                          steps:
                            - setup_remote_docker:
                                version: 20.10.11
                            - checkout
                            - run:
                                name: "Deploy to Astro"
                                command: |
                                  curl -sSL install.astronomer.io | sudo bash -s
                                  astro deploy $rcm2yvgdiw059201i3kwpar6ep -f
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1730489242443
        repoName: annieastronomer/test2
        build: <+input>
